const express=require("express")
const app=express()
const router=express.Router()
const cors = require("cors")
const mongoose = require("mongoose")
const bodyParser = require("body-parser")
const ContactManager= require("./routes/ContactManagerRoutes")
const Bookroutes=require("./routes/bookroutes")
//const Todocontroller=require("./routes/todoroutes")
app.use(bodyParser.json())
app.use(cors())
app.use("/",ContactManager)
app.use("/",Bookroutes)
//app.use("/",Todocontroller)
mongoose.connect("mongodb://localhost:27017/c1sinon").then((res)=>console.log("connecting")).catch((err)=>console.log(err))
app.listen(3001,()=>console.log("server started"))